vault_dirpath: path/to/your_vault
index_dirpath: ./data/indexes/mecab/
stopwords_filepath: ./data/stopwords.txt
exclude_dirnames:
  - templates
reindex_interval: 600 # (sec)
indexing_threads: null
api_host: 127.0.0.1
api_port: 8000
